// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/agenda/:slug": {
    params: {
      "slug": string;
    };
  };
  "/agenda/:slug/add": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/agenda/:slug" | "/agenda/:slug/add";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/agenda.$slug.jsx": {
    id: "routes/agenda.$slug";
    page: "/agenda/:slug";
  };
  "routes/agenda.$slug.add.jsx": {
    id: "routes/agenda.$slug.add";
    page: "/agenda/:slug/add";
  };
};